#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

printf "\n\360\237\215\272\t Running pre-commit hook...  \n"

printf "\n\360\237\215\272\t Running linter...  \n"
npm run lint
printf "\n\360\237\215\272\t Running format...  \n"
npm run format
